### ISSUE TITLE
Store environment config files in a `binder` directory ?

### ISSUE THREAD

**Issue by pierrepo** [plasmabio/template-bash#2]
It might be a good practice to keep all config files of the environment in a `binder` directory. This is enabled by [repod2docker](https://repo2docker.readthedocs.io/en/latest/usage.html#where-to-put-configuration-files).

This would prevent the user from seeing files he doesn't need (in the first place).

We may then bring notebooks and files from the `materials` directory back to the root directory of the env.

Could you share your thoughs on this @jtpio ?

**Comment by jtpio** [comment]
Sounds good :+1: 

Many repos adopt this convention to keep things tidy indeed.

`.binder/` would also work, since the notebook and lab interfaces do not show hidden files by default?

**Comment by pierrepo** [comment]
> .binder/ would also work, since the notebook and lab interfaces do not show hidden files by default?

Absolutely. But I'd like to let more curious students engage with the env by keeping the `binder` directory available. 

From a teaching point-of-view, this is also a very good opportunity to speak about reproducibility: "All the things you have to now about your env is in `binder/`" ;-)

**Comment by jtpio** [comment]
Good points.

Then `binder/` sounds like the best option.

**Comment by pierrepo** [comment]
Awesome @jtpio 
I'll update the template repo soon.
