### ISSUE TITLE
less not working in jupyterlab notebook

### ISSUE THREAD

**Issue by CVandiedonck** [plasmabio/template-bash#4]
It works in the terminal but not in a cell. A message is displayed: "WARNING: terminal is not fully functional"
Is this normal?
When trying to use it, it actually froze my environment.

**Comment by pierrepo** [comment]
It's not a bug, it's a feature ;-) 
Programs such as less, more or nano expect interactivity with the user. Such interactivity is not possible within a notebook cell.

**Comment by CVandiedonck** [comment]
I see, thanks.
